// Single source of truth for the batchVersion write shape, shared by the two
// contract producers (optimistic commit and runTransaction) and the future
// Worker REST path. When a current version exists the write is a CAS-style
// update carrying it as prevVersion; the very first write has no predecessor
// and is created unconditionally with an empty prevVersion (see
// firestore.rules — the initial doc goes through the unconditional `create`
// clause, not the `__INITIAL__` update clause). `newUuid` is generated by the
// caller so this stays pure.
export function nextBatchVersionWrite(
  currentVersion: string | undefined,
  newUuid: string,
): { op: "set" | "update"; data: { prevVersion: string; version: string } } {
  if (currentVersion) {
    return { op: "update", data: { prevVersion: currentVersion, version: newUuid } };
  }
  return { op: "set", data: { prevVersion: "", version: newUuid } };
}
