// uuidv7 encodes a 48-bit big-endian Unix millisecond timestamp in its first 48 bits
// (the leading 12 hex digits of the canonical string). Extracting it lets a document id
// generated by uuidv7() be compared against a time cutoff without a separate timestamp
// field. Returns NaN when the input does not start with hex digits.
export function uuidV7ToMs(uuid: string): number {
  const hex = uuid.replace(/-/g, "").slice(0, 12);
  return parseInt(hex, 16);
}
